### ISSUE TITLE
[mapping] Printing map

### ISSUE THREAD

**Issue by gilbertfrausto** [MetropolitanTransportationCommission/vpp-webapp#66]
Look at ersi vs Media print

**Comment by Keareys** [comment]
Layers are not displaying correctly on printout. Please review and determine if this can be fixed.

**Comment by MTCGIS** [comment]
Confirm that the print map display is working correctly when creating a pdf from the current map view.  May need to fix legend div on map so that the center of the map is in the center of the printout for the map display.  The legend is covering up part of the sutdy area when creating the map printout.  Can we offset/resize the div on the map printout to correct for this behaviour?
